platform: linux
image_resource:
  source:
    repository: cryogenics/essentials
    tag: latest
  type: registry-image

params:
  GCP_SERVICE_ACCOUNT_KEY: ((gcp/service_accounts/owner.json_key))
  DEBUG: # any value will turn Debug mode on. Remove the param to disable debug.

inputs:
  - name: env
  - name: backup-and-restore-sdk-release
run:
  path: backup-and-restore-sdk-release/ci/tasks/allow-tunnel-from-jumpbox-to-database-vms/task.sh

